[phases.setup]
aptPkgs = [
  "libnss3",
  "libx11-6",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libasound2t64",
  "libatk1.0-0t64",
  "libatk-bridge2.0-0t64",
  "libpangocairo-1.0-0t64",
  "libcups2t64",
  "fonts-liberation",
  "fonts-noto-color-emoji",
  "fonts-unifont"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]
